# Default locale for UI strings
# Available UI languages: en, fr, de, sv
locale: "fr"

# Available themes: bulma, chota, dsfr
# You can set the theme on the command line with
# clj -X:set :theme bulma
theme: "dsfr"

# Customize UI strings
ui-strings:
  # copy-to-clipboard:    "Copy in the clipboard"
  mail-to-message:      "Send by email"
  mail-subject:         "Guide interactif sur la publication des codes sources : demande d'aide ou d'informations"
  mail-body:            "Bonjour, je viens d'utiliser votre guide pour la publication des codes sources de l'administration. Voici les résultats que j'obtiens: %s Je souhaite plus d'informations..."
  redo:                 "Redo"
  # ok:                   "Okay"
  # contact-intro:        "Contact: "
  # toggle-summary-style: "Toggle summary style"
  # attention:            "Attention"

# Website header
header:
 title:    "« En tant qu'organisme public, dois-je publier ce code source ? »"
 subtitle: "Guide juridique interactif sur la publication des codes sources de l'administration."

# Website footer
footer:
 text:    "Ce site a été réalisée par la mission [Etalab](https://www.etalab.gouv.fr) en 2019.  Il est maintenu par la [mission logiciels libres](https://code.gouv.fr) de la DINUM.  Vous pouvez lire son [code source](https://github.com/codegouvfr/guide-juridique)."
 contact:  "floss@numerique.gouv.fr"

# Allow users to send you emails with the summary?
mail-to: "floss@numerique.gouv.fr"

# Display summary when done?
display-summary: true

# Display score information?
display-score: false

# Display each score?
# Mostly useful for debugging
display-score-details: false

# Display the score with the highest value?
# Only when :as-top-result-display is set for each score
display-score-top-result: false

# In a branch of the tree, should the target node be set depending on
# the updated value of conditional-score-output?
conditional-navigation: false

# Some text message to always display after the score results
display-unconditionally: false

# Set initial variables to register scores.
score-variables:
  # "score-1" is a user-defined string
  score-1:
    # What to display when displaying score details:
    #display: "Votre score Awesome CodeGouvFr est de "
    # Initial value for score-1:
    value: 0
    # When you when the score message to use percent:
    as-percent: true
    # Max is needed for displaying percent:
    max: 10
    # Only needed when display-score-top-result is true
    #as-top-result-display: "1 wins :)"

# Set conditional output depending on scores.
# conditional-score-output:
#   # Cases are tested one by one.  The first case that matches is the
#   # main score.  When case have a priority value, the matching case
#   # with the highest priority is the main score.
#   cas-1: # free-form condition name
#     # priority: 2 # Use priority to matching order
#     color: "is-success" # Bulma-based class names for the UI
#     # notification.  Available values for colors are: is-success,
#     # is-info, is-warning, is-danger.
#     message: "Bravo, vous satisfaites %score-1% des critères !"
#     # In score-variables, when :max is set and :as-percent is true,
#     # then the score will be shown as a percentage.
#     condition-1:
#       score-1: 8 # This condition is met when score-1 is >= 2
#   cas-2:
#     color: "is-warning"
#     message: "%score-1%, pas mal ! Rendez-vous sur notre [documentation](https://code.gouv.fr/documentation/#/publier) pour progresser."
#     condition-1:
#       score-1: 6 # This condition is met when score-1 is >= 1
#   cas-3:
#     color: "is-danger"
#     message: "À %score-1%, il y a encore un peu de travail.  Rendez-vous sur la [doc](https://code.gouv.fr/documentation/#/publier) pour progresser."
#     condition-1:
#       score-1: 0 # This condition is met when score-1 is >= 0

# Mandatory configuration option
tree:
  - node:       "0"
    text:       "Pourquoi ce guide ?"
    home-page:  true
    no-summary: true
    help:       "Depuis 2005, la loi a affirmé un droit de réutilisation des informations publiques. Celle-ci concerne à la fois les données publiques (« open data ») et les logiciels (« libres »).  L'esprit de la réutilisation est d'être la plus libre possible, afin de favoriser les usages. Depuis décembre 2015, la réutilisation gratuite constitue la règle, pour les données comme pour les logiciels.<br/><br/>Ce guide s'adresse aux administrations publiques qui détiennent les droits de propriété intellectuelle leur permettant d'établir une licence logicielle : il permet de savoir le quoi et le comment de la publication, et propose de vous aider à choisir entre les deux grandes familles de licences libres"
    choices:
    - answer: "Commencer"
      goto:   "1"
      color:  "is-success"

  - node:       "1"
    progress:   "[0 10]"
    text:       "Produisez-vous ou recevez-vous un logiciel, dans le cadre de l'exercice d'une mission de service public ?"
    start-page: true
    help: "Un logiciel est un ensemble des programmes, procédés et règles, et éventuellement de documentations, relatifs au fonctionnement d'un ensemble de traitement de données. Une mission de service public relève d'une activité d'intérêt général menée sous le contrôle de l'administration avec des prérogatives de puissance publique."
    choices:
    - answer:  "Oui"
      summary: "Vous produisez ou recevez un [document administratif](https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000033218936&cidTexte=LEGITEXT000031366350&dateTexte=20161009) qui doit être communiqué pourvu qu'il ait un intérêt économique, social, sanitaire ou environnemental."
      goto:    "2"
      color:   "is-success"
    - answer:  "Non"
      summary: "Vous ne produisez ou ne recevez pas de [document administratif](https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000033218936&cidTexte=LEGITEXT000031366350&dateTexte=20161009), vous n'avez pas à établir une licence de réutilisation de données publiques."
      color:   "is-warning"
      goto:    "end-1"

  - node:     "2"
    progress: "[1 10]"
    text:     "Votre logiciel peut-il être considéré comme « achevé » ?"
    help:     "Le droit à communication ne s'applique qu'à des [documents achevés](https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000031367700&cidTexte=LEGITEXT000031366350&dateTexte=20160101).  Un logiciel peut être considéré comme « achevé » dès lors que, dans l'exercice d'une mission de service public, il est déployé en production, est utilisé par des agents publics ou implémente un premier périmètre de fonctionnalités.  Un logiciel n'a pas besoin d'être en version 1.0 ou de sortir des statuts « alpha » ou « bêta » pour être considéré comme achevé."
    choices:
    - answer:  "Oui"
      summary: "Votre logiciel est utilisé en production."
      goto:    "3"
      color:   "is-success"
    - answer:  "Non"
      summary: "Votre logiciel ne peut pas être considéré comme achevé, vous n'êtes pas tenu de le communiquer.  Toutefois, il est de bonne pratique de publier les codes sources de vos logiciels dès la première ligne de code source écrite."
      color:   "is-warning"
      goto:    "end-1"

  - node:     "3"
    progress: "[2 10]"
    text:     "Le code source contient-il des secrets faisant obstacle à la communication du logiciel ?"
    help: "La présence de secrets dans un code source peut empêcher la publication du logiciel associé.<br/><br/>Il peut s'agir d'un [secret absolu](https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000033265181&cidTexte=LEGITEXT000031366350&dateTexte=20170701) : certains logiciels, dans l'intérêt public, ne peuvent être rendus publics par vous, notamment pour des questions sécuritaires et de sûreté nationale. <br/><br/>Le secret peut aussi être [relatif](https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=9E840349D3C48307C89BEA8DBA9C48B2.tplgfr23s_2?idArticle=LEGIARTI000033218964&cidTexte=LEGITEXT000031366350&dateTexte=20170701), comme des informations relatives à la vie privée d'une personne, des informations comportant une appréciation ou un jugement de valeur sur une personne physique ou des informations commerciales et industrielles risquant de porter préjudice à un acteur économique.  Dans ce cas, le code source du logiciel n'est communicable qu'aux personnes pour qui ces informations n'ont pas à rester secrètes."
    choices:
    - answer:  "Non"
      summary: "Votre logiciel ne contient pas de secret légal, relatif ou absolu."
      goto: "5"
      color: "is-success"
    - answer:  "Oui"
      summary: "Votre logiciel est grevé par un secret. S'il est absolu, ces informations ne peuvent être communiquées à quiconque. S'il est relatif,  ces informations ne peuvent qu'être communiquées aux personnes directement concernées.."
      color: "is-warning"
      goto: "4"

  - node: "4"
    progress: "[3 10]"
    text: "Est-il possible d'occulter les éléments relevant d'un secret par un traitement automatisé d'usage courant sans que cela ne dénature ni ne vide de son sens le document ?"
    help: "La communication des documents administratifs peut exiger d'[occulter](https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=9E840349D3C48307C89BEA8DBA9C48B2.tplgfr23s_2?idArticle=LEGIARTI000031367719&cidTexte=LEGITEXT000031366350&dateTexte=20170701) les secrets qu'ils contienneent.  Un document est « dénaturé » ou « vidé » de son sens s'il ne contient plus de données ou si les données clé pour la compréhension du document sont enlevées."
    choices:
    - answer: "Oui"
      summary: "Vous devez occulter des éléments."
      color: "is-success"
      goto: "7"
    - answer: "Non"
      summary: "Vous ne pouvez pas occulter ces éléments, vous ne pouvez pas publier ce logiciel."
      color: "is-warning"
      goto: "end-1"

  - node: "5"
    progress: "[4 10]"
    text: "Votre logiciel est-il composé d'éléments protégés par des droits tiers, par exemple extraits du code source d'autres logiciels ?"
    help: "La diffusion du logiciel au public peut être empêchée par [la détention, par un tiers, de droits de propriété intellectuelle sur une partie de votre logiciel](https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000031366350&idArticle=LEGIARTI000033219038). Ce dernier peut, par exemple, être construit à partir d'éléments d'autres logiciels qui peuvent être protégés par des licences. <br/><br/> Une licence est un contrat par lequel le concepteur du logiciel en autorise l'exploitation par un tiers sous certaines conditions. Elle peut être libre, l'auteur concède alors tout ou partie de ses droits, en laissant au minimum 4 droits considérés fondamentaux aux utilisateurs (usage, étude, modification et redistribution de l'œuvre). Une licence explicite l'existence de droits tiers, mais il peut en exister même lorsqu'il n'y a pas de licence."
    choices:
    - answer: "Non"
      summary: "Il n'existe pas de droits tiers sur le code source de votre logiciel."
      color: "is-success"
      goto: "7"
    - answer: "Oui, des éléments publiés sous licence libre."
      summary: "Votre logiciel intègre du code source tiers publié sous licence libre."
      color: "is-warning"
      goto: "7"
    - answer: "Oui, des éléments qui ne sont pas publiés sous licence libre."
      summary: "Votre logiciel intègre du code source tiers qui n'est pas publié sous licence libre."
      goto: "6"
      color: "is-danger"
      
  - node: "6"
    progress: "[5 10]"
    text: "Est-il possible de publier votre logiciel séparément des éléments relevant de droits tiers, sans que cela ne dénature ni ne vide de son sens le logiciel ?"
    help: "Un document est « dénaturé » ou « vidé » de son sens s'il ne contient plus de données ou si les données-clés pour sa compréhension ne sont pas disponibles."
    choices:
    - answer: "Oui"
      summary: "Il est possible d'occulter les éléments relevant de droits tiers. Vous devez occulter ces éléments"
      color: "is-success"
      goto: "7"
    - answer: "Non"
      summary: "Vous ne pouvez pas occulter ces éléments relevant de droits tiers."
      color: "is-warning"
      goto: "end-1"

  - node: "7"
    progress: "[6 10]"
    text: "Êtes-vous juridiquement contraint par les droits tiers des logiciels libres à un choix limité de licences ?"
    help: "Si le code source de votre logiciel intègre des codes sources publiés sous licence libre, la licence de ses éléments peut limiter votre choix de licence.  Par exemple, si votre code source intègre du code source publié sous licence GNU GPL, vous devrez utiliser la licence GNU GPL ou une licence compatible pour votre propre code source."
    choices:
    - answer: "Non"
      summary: "Le choix de votre licence est libre."
      color: "is-success"
      goto: "8"
    - answer: "Oui"
      summary: "Le choix de la licence est limité à celles qui vous sont autorisées par les licences des logiciels intégrés dans le vôtre."
      color: "is-warning"
      goto: "end-3"

  - node: "8"
    progress: "[7 9]"
    text: "Des motifs d'intérêt général pourraient-ils limiter la libre réutilisation ?"
    help: "Vous devez choisir parmi une [liste de licences](https://www.data.gouv.fr/fr/licences) qui peuvent être utilisées par les administrations pour la réutilisation à titre gratuit de leurs informations publiques. Par défaut, vous devez opter pour une licence permissive.  Si toutefois vous souhaitiez apporter des restrictions à la réutilisation, vous pouvez utiliser des licences dites « à réciprocité », à condition que ces restrictions soient justifiées par des motifs d'intérêt général et s'appliquent de façon proportionnée (cf. l'article [L323-2](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000033219073/) du CRPA.)"
    choices:
    - answer: "Non"
      summary: "La libre réutilisation du logiciel peut se faire sans limite."
      color: "is-success"
      goto: "end-5"
    - answer: "Oui"
      summary: ["La libre réutilisation du logiciel doit être limitée, Étant entendu que cette limitation doit être proportionnée et ne doit pas avoir pour objet ou pour effet de porter atteinte à la concurrence.", "Vous devez opter pour une licence avec obligation de réciprocité."]
      color: "is-warning"
      goto: "end-4"

  - node: "end-1"
    progress: "[10 10]"
    text: "Vous n'êtes pas soumis au régime des documents administratifs."
    done: true
  - node: "end-2"
    text: "Vous établirez une licence pour votre logiciel, mais celle-ci ne devra pas nécessairement faire partie de la liste des licences fixées par décret."
    done: true
  - node: "end-3"
    text: "Vous publierez le code source de votre logiciel ; vous êtes limités dans votre choix de licence par les éléments que vous avez incorporés dans le code source de votre logiciel."
    done: true
  - node: "end-4"
    text: "Vous publierez votre logiciel et [opterez pour une licence avec obligation de réciprocité](https://www.data.gouv.fr/fr/licences)."
    done: true
  - node: "end-5"
    text: "Vous publierez votre logiciel et [opterez pour une licence permissive](https://www.data.gouv.fr/fr/licences)."
    done: true
